--- #YAML:1.0
name:                Class-DBI-AutoIncrement-Simple
version:             0.01
abstract:            Add autoincrementing to a Class::DBI subclass
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              David Westbrook <dwestbrook@gmail.com>
distribution_type:   module
requires:     
    Class::DBI:                    0
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
